// Demo data — realistic sample shipments (NOT real customer data)

export const CITIES = {
  Mumbai: [72.8777, 19.076],
  Dubai: [55.2708, 25.2048],
  Rotterdam: [4.4777, 51.9244],
  Frankfurt: [8.6821, 50.1109],
  "New York": [-74.006, 40.7128],
  Shenzhen: [114.0579, 22.5431],
  Singapore: [103.8198, 1.3521],
  "Los Angeles": [-118.2437, 34.0522],
  Chicago: [-87.6298, 41.8781],
  Shanghai: [121.4737, 31.2304],
  Hamburg: [9.9937, 53.5511],
  London: [-0.1276, 51.5072],
  Tokyo: [139.6917, 35.6895],
  "San Francisco": [-122.4194, 37.7749],
  Sydney: [151.2093, -33.8688],
  Santos: [-46.3336, -23.9608],
  Antwerp: [4.4025, 51.2194],
  Memphis: [-90.049, 35.1495],
};

export const STATUS = {
  in_transit: { label: "In Transit", color: "#007AFF", dot: "🟢" },
  delivered: { label: "Delivered", color: "#34C759" },
  delayed: { label: "Delayed", color: "#FF9500" },
  held: { label: "Held", color: "#FFCC00" },
  exception: { label: "Exception", color: "#FF3B30" },
};

export const SHIPMENTS = [
  {
    id: "CT-10245",
    status: "in_transit",
    mode: "Ocean",
    origin: "Shenzhen",
    destination: "Chicago",
    eta: "Aug 14, 2026",
    carrier: "Maersk Line",
    tracking: "MAEU-784512360",
    current: "Pacific Ocean — 1,240 nm from Long Beach",
    route: ["Shenzhen", "Singapore", "Los Angeles", "Chicago"],
  },
  {
    id: "CT-10188",
    status: "delayed",
    mode: "Multimodal",
    origin: "Mumbai",
    destination: "New York",
    eta: "Aug 19, 2026",
    carrier: "MSC + DB Schenker",
    tracking: "MSCU-1190447",
    current: "Rotterdam Port",
    route: ["Mumbai", "Dubai", "Rotterdam", "Frankfurt", "New York"],
  },
  {
    id: "CT-10422",
    status: "delivered",
    mode: "Air",
    origin: "Tokyo",
    destination: "San Francisco",
    eta: "Aug 03, 2026",
    carrier: "ANA Cargo",
    tracking: "NH-205-88471",
    current: "Delivered — San Francisco DC",
    route: ["Tokyo", "San Francisco"],
  },
  {
    id: "CT-10510",
    status: "held",
    mode: "Ocean",
    origin: "Santos",
    destination: "Hamburg",
    eta: "Aug 22, 2026",
    carrier: "Hapag-Lloyd",
    tracking: "HLCU-664021",
    current: "Antwerp — Customs hold",
    route: ["Santos", "Antwerp", "Hamburg"],
  },
  {
    id: "CT-10633",
    status: "exception",
    mode: "Road",
    origin: "Los Angeles",
    destination: "Chicago",
    eta: "Aug 11, 2026",
    carrier: "J.B. Hunt",
    tracking: "JBHT-4471200",
    current: "I-80 near Omaha — weather exception",
    route: ["Los Angeles", "Chicago"],
  },
  {
    id: "CT-10701",
    status: "in_transit",
    mode: "Rail",
    origin: "Shanghai",
    destination: "London",
    eta: "Aug 26, 2026",
    carrier: "DB Cargo",
    tracking: "DBC-9920014",
    current: "Trans-Eurasia Rail — Malaszewicze",
    route: ["Shanghai", "Hamburg", "London"],
  },
];

export const JOURNEY = [
  { key: "picked_up", label: "Picked Up", done: true },
  { key: "origin_facility", label: "Origin Facility", done: true },
  { key: "export_customs", label: "Export Customs", done: true },
  { key: "port", label: "Port", done: true },
  { key: "vessel_departed", label: "Vessel Departed", done: true },
  { key: "ocean_transit", label: "Ocean Transit", done: true, active: true },
  { key: "dest_port", label: "Destination Port", done: false },
  { key: "customs", label: "Customs", done: false },
  { key: "final_mile", label: "Final Mile", done: false },
  { key: "delivered", label: "Delivered", done: false },
];

export const LIFECYCLE = [
  "Order Created", "Pre-Dispatch", "Picked Up", "Warehouse / Facility",
  "Dispatched", "In Transit", "Port / Terminal", "Customs",
  "Destination Facility", "Out for Delivery", "Delivered",
];

export const DASHBOARD = {
  active: 12482,
  breakdown: [
    { label: "In Transit", value: 8421, color: "#007AFF" },
    { label: "At Facility", value: 1204, color: "#5856D6" },
    { label: "Delayed", value: 834, color: "#FF9500" },
    { label: "Held", value: 241, color: "#FFCC00" },
    { label: "Exceptions", value: 152, color: "#FF3B30" },
    { label: "Delivered", value: 1630, color: "#34C759" },
  ],
  byMode: [
    { name: "Ocean", value: 5120 },
    { name: "Road", value: 3980 },
    { name: "Air", value: 1890 },
    { name: "Rail", value: 892 },
    { name: "Multimodal", value: 600 },
  ],
  etaPerf: [
    { week: "W1", onTime: 91, delayed: 9 },
    { week: "W2", onTime: 88, delayed: 12 },
    { week: "W3", onTime: 93, delayed: 7 },
    { week: "W4", onTime: 90, delayed: 10 },
    { week: "W5", onTime: 94, delayed: 6 },
    { week: "W6", onTime: 92, delayed: 8 },
  ],
  byCountry: [
    { country: "United States", value: 3120 },
    { country: "China", value: 2740 },
    { country: "Germany", value: 1560 },
    { country: "India", value: 1290 },
    { country: "Netherlands", value: 980 },
    { country: "Singapore", value: 760 },
  ],
  byCarrier: [
    { carrier: "Maersk Line", mode: "Ocean", onTime: 94, exceptions: 12, shipments: 2140 },
    { carrier: "DB Schenker", mode: "Rail", onTime: 91, exceptions: 18, shipments: 1680 },
    { carrier: "ANA Cargo", mode: "Air", onTime: 96, exceptions: 6, shipments: 1120 },
    { carrier: "Hapag-Lloyd", mode: "Ocean", onTime: 88, exceptions: 27, shipments: 1540 },
    { carrier: "J.B. Hunt", mode: "Road", onTime: 90, exceptions: 21, shipments: 1980 },
    { carrier: "MSC", mode: "Ocean", onTime: 85, exceptions: 34, shipments: 2020 },
  ],
};

// Post-purchase customer notification journey (for the animated preview)
export const NOTIFICATIONS = [
  { channel: "Email", title: "Order Confirmed", body: "Your order CT-10245 has been confirmed.", time: "9:04 AM" },
  { channel: "SMS", title: "Picked Up", body: "Good news — your shipment was picked up in Shenzhen.", time: "11:20 AM" },
  { channel: "Push", title: "In Transit", body: "Your shipment has departed on MV Nordic Star.", time: "6:45 PM" },
  { channel: "Email", title: "At Customs", body: "Shipment arrived at customs. No action needed from you.", time: "8:12 AM" },
  { channel: "SMS", title: "Customs Cleared", body: "Cleared customs — back on the move to Chicago.", time: "2:30 PM" },
  { channel: "Push", title: "Out for Delivery", body: "Arriving today between 1–4 PM. Track live.", time: "9:15 AM" },
  { channel: "Email", title: "Delivered", body: "Delivered to Chicago DC. Proof of delivery attached.", time: "3:48 PM" },
];
